services:
  web:
    build: .
    container_name: debian_web_server
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: debian_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
